### ISSUE TITLE
Footnotes do not appear correctly

### ISSUE THREAD

**Issue by josieg** [BCcampus/pressbooks-mpdf#77] opened 2019-04-10 21:30 UTC
### Description 

Content in footnotes appears in a smaller font but inline with the rest of the text.

**Expected behaviour** 
I expect that a superscript number should mark the spot where a footnote belongs and that the footnote content will be placed at the end of the page where it appears (same behaviour as Prince).
_Screenshot from Print PDF (Prince)_
![PrincePDF](https://user-images.githubusercontent.com/23706762/55914531-3d1f5480-5b9c-11e9-967e-b9eb52c202b9.jpg)

**Actual behaviour** 
Content in footnotes appears in a smaller font but inline with the rest of the text.
_MPDF Screenshot (I've highlighted the text that should be in a footnote.)_
![MPDF](https://user-images.githubusercontent.com/23706762/55914449-09dcc580-5b9c-11e9-835c-83cc18111626.jpg)

### Steps to reproduce the problem

1. Insert a footnote with content. (For example: https://pressbooksdev.bccampus.ca/foundations/front-matter/foundations-guide-overview/)
2. Export book as MPDF.
3. Look at the appearance of the footnote in that file format.

### System Information

- mPDF for Pressbooks: 3.3.0
- Pressbooks: 5.7.0
- WordPress: 5.1.1

**Comment by bdolor** [comment] 2019-04-10 21:37
thanks @josieg - the bulk of this looks like a duplicate of https://github.com/BCcampus/pressbooks-mpdf/issues/2 ?

**Comment by josieg** [comment] 2019-04-10 21:40
Gahh I knew the issue felt familiar but I searched for footnotes in this repo and couldn't find it. Whoops. Please delete

**Closed as completed** 2019-04-10 21:45 UTC
Labels: duplicate
